In [1177]:
import pandas as pd
from sqlalchemy import create_engine
from sqlalchemy import text

In [1178]:
df = pd.read_csv("g14_Airports_Airlines.csv", encoding='latin1', sep = ';', parse_dates=['build_date','flight_date'], dayfirst=True)

In [1179]:
df = df.drop_duplicates()

In [1180]:
df.head()

,airport_id,airline_id,flight_date,ticket_cost,name,build_date,denomination,class,terminal_id,notes
0,136,24,2025-03-08,1666,"Brady, Walton and Horn",2021-07-26,Swiss International Air Lines,Alliance Airline,78.0,alone
1,423,20,2024-11-22,1518,Coleman LLC,2024-10-07,Aer Lingus,Hybrid Carrier,120.0,available
2,423,16,2024-12-26,1518,Coleman LLC,2024-10-07,Japan Airlines,Full-Service Carrier,159.0,military
3,218,25,2023-05-11,2530,Lucero-Stewart,2023-03-09,Austrian Airlines,Charter Airline,36.0,him
4,218,15,2023-04-11,2530,Lucero-Stewart,2023-03-09,ANA (All Nippon Airways),Regional Airline,166.0,religious

In [1181]:
df.insert(0, 'voo_id', range(1, len(df) + 1))

In [1182]:
df.head()

,voo_id,airport_id,airline_id,flight_date,ticket_cost,name,build_date,denomination,class,terminal_id,notes
0,1,136,24,2025-03-08,1666,"Brady, Walton and Horn",2021-07-26,Swiss International Air Lines,Alliance Airline,78.0,alone
1,2,423,20,2024-11-22,1518,Coleman LLC,2024-10-07,Aer Lingus,Hybrid Carrier,120.0,available
2,3,423,16,2024-12-26,1518,Coleman LLC,2024-10-07,Japan Airlines,Full-Service Carrier,159.0,military
3,4,218,25,2023-05-11,2530,Lucero-Stewart,2023-03-09,Austrian Airlines,Charter Airline,36.0,him
4,5,218,15,2023-04-11,2530,Lucero-Stewart,2023-03-09,ANA (All Nippon Airways),Regional Airline,166.0,religious

In [1183]:
engine = create_engine('sqlite:///Airport airlines - 2.db')

In [1184]:
#Terminal

In [1185]:
df_terminal = df.loc[:,['terminal_id','notes','airport_id']]

In [1186]:
df_terminal.head(3)

   terminal_id      notes  airport_id
0         78.0      alone         136
1        120.0  available         423
2        159.0   military         423

In [1187]:
df_terminal = df_terminal.drop_duplicates(subset='terminal_id', keep='first')

In [1188]:
df_terminal = df_terminal.loc[df_terminal['terminal_id'].notnull()]

In [1189]:
df_terminal.rename(columns={'terminal_id':'id'}, inplace=True)

In [1190]:
df_terminal.head(3)

      id      notes  airport_id
0   78.0      alone         136
1  120.0  available         423
2  159.0   military         423

In [1191]:
with engine.begin() as conn:
    conn.execute(text("DELETE FROM Terminal;"))
#ao usar o append na de baixo, se ja estiverem la dados estes nao sao apagados. por isso, ao adicionar la novos vai dar erro se forem iguais aos existentes (pk implica que so haja uma linha com esse valor)
#havia duas formas de resolver isto: 1 - ao inserir, se o dado ja existir na tabela, ignorar ou replace (mas isso ja seria muito complicado!) ou 2 (usada aqui) - apagar todos os dados da tabela antes de inserir novos
#como neste exercicio estamos perante a inicializacao de uma tabela a partir de dados de um ficheiro csv, faz sentido usar a segunda opcao

In [1192]:
df_terminal.to_sql('Terminal', con=engine, if_exists='append', index=False) 
#nao posso usar aqui if_exists='replace' pq assim estraga me as pk e fk

200

In [1193]:
#Airport

In [1194]:
df_airport = df.loc[:,['airport_id','build_date','name']]

In [1195]:
df_airport.head(3)

   airport_id build_date                    name
0         136 2021-07-26  Brady, Walton and Horn
1         423 2024-10-07             Coleman LLC
2         423 2024-10-07             Coleman LLC

In [1196]:
df_airport = df_airport.drop_duplicates(subset='airport_id', keep='first')

In [1197]:
df_airport = df_airport.loc[df_airport['airport_id'].notnull()]

In [1198]:
df_airport.rename(columns={'airport_id':'id'}, inplace=True)

In [1199]:
df_airport.head(3)

    id build_date                    name
0  136 2021-07-26  Brady, Walton and Horn
1  423 2024-10-07             Coleman LLC
3  218 2023-03-09          Lucero-Stewart

In [1200]:
with engine.begin() as conn:
    conn.execute(text("DELETE FROM Airport;"))
#ao usar o append na de baixo, se ja estiverem la dados estes nao sao apagados. por isso, ao adicionar la novos vai dar erro se forem iguais aos existentes (pk implica que so haja uma linha com esse valor)
#havia duas formas de resolver isto: 1 - ao inserir, se o dado ja existir na tabela, ignorar ou replace (mas isso ja seria muito complicado!) ou 2 (usada aqui) - apagar todos os dados da tabela antes de inserir novos
#como neste exercicio estamos perante a inicializacao de uma tabela a partir de dados de um ficheiro csv, faz sentido usar a segunda opcao

In [1201]:
df_airport.to_sql('Airport', con=engine, if_exists='append', index=False) 
#nao posso usar aqui if_exists='replace' pq assim estraga me as pk e fk

500

In [1202]:
#Airline

In [1203]:
df_airline = df.loc[:,['airline_id','denomination','class']]

In [1204]:
df_airline.head(3)

   airline_id                   denomination                 class
0          24  Swiss International Air Lines      Alliance Airline
1          20                     Aer Lingus        Hybrid Carrier
2          16                 Japan Airlines  Full-Service Carrier

In [1205]:
df_airline = df_airline.drop_duplicates(subset='airline_id', keep='first')

In [1206]:
df_airline = df_airline.loc[df_airline['airline_id'].notnull()]

In [1207]:
df_airline.rename(columns={'airline_id':'id', 'class':'classe'}, inplace=True)

In [1208]:
df_airline.head(3)

   id                   denomination                classe
0  24  Swiss International Air Lines      Alliance Airline
1  20                     Aer Lingus        Hybrid Carrier
2  16                 Japan Airlines  Full-Service Carrier

In [1209]:
with engine.begin() as conn:
    conn.execute(text("DELETE FROM Airline;"))
#ao usar o append na de baixo, se ja estiverem la dados estes nao sao apagados. por isso, ao adicionar la novos vai dar erro se forem iguais aos existentes (pk implica que so haja uma linha com esse valor)
#havia duas formas de resolver isto: 1 - ao inserir, se o dado ja existir na tabela, ignorar ou replace (mas isso ja seria muito complicado!) ou 2 (usada aqui) - apagar todos os dados da tabela antes de inserir novos
#como neste exercicio estamos perante a inicializacao de uma tabela a partir de dados de um ficheiro csv, faz sentido usar a segunda opcao

In [1210]:
df_airline.to_sql('Airline', con=engine, if_exists='append', index=False)
#nao posso usar aqui if_exists='replace' pq assim estraga me as pk e fk

50

In [1211]:
#Voo

In [1212]:
df_voo = df.loc[:,['voo_id','airline_id','airport_id','flight_date','ticket_cost']]

In [1213]:
df_voo.head(3)

   voo_id  airline_id  airport_id flight_date  ticket_cost
0       1          24         136  2025-03-08         1666
1       2          20         423  2024-11-22         1518
2       3          16         423  2024-12-26         1518

In [1214]:
df_voo = df_voo.loc[df_voo['voo_id'].notnull()]

In [1215]:
df_voo.rename(columns={'voo_id':'id'}, inplace=True)

In [1216]:
df_voo.head(3)

   id  airline_id  airport_id flight_date  ticket_cost
0   1          24         136  2025-03-08         1666
1   2          20         423  2024-11-22         1518
2   3          16         423  2024-12-26         1518

In [1217]:
with engine.begin() as conn:
    conn.execute(text("DELETE FROM Voo;"))
#ao usar o append na de baixo, se ja estiverem la dados estes nao sao apagados. por isso, ao adicionar la novos vai dar erro se forem iguais aos existentes (pk implica que so haja uma linha com esse valor)
#havia duas formas de resolver isto: 1 - ao inserir, se o dado ja existir na tabela, ignorar ou replace (mas isso ja seria muito complicado!) ou 2 (usada aqui) - apagar todos os dados da tabela antes de inserir novos
#como neste exercicio estamos perante a inicializacao de uma tabela a partir de dados de um ficheiro csv, faz sentido usar a segunda opcao

In [1218]:
df_voo.to_sql('Voo', con=engine, if_exists='append', index=False) 
#nao posso usar aqui if_exists='replace' pq assim estraga me as pk e fk

10692

In [1219]:
#é preciso mais alguma coisa? result=... ou df.to_csv...?

In [1220]:
engine.dispose()